### ISSUE TITLE
Improve time display

### ISSUE THREAD

**Issue by ouioui2003** [pleonex/Ninokuni#4]
Hi,

Here is a enhancement:
When you want to really finish the game, you can spend many time to do it.
The timer saved in the saved game only show hours before 100.

If the game save a timestamp in the saved file, it could be nice to have the real time shown on the screen.
Add one more digit on hours and the game can display at least 999 hours !

![time](https://cloud.githubusercontent.com/assets/10521705/5870830/4cbfbb2a-a2d5-11e4-98d0-833fe1d43598.png)

Thanks for that !

**Comment by pleonex** [comment]
Good idea!
I will add it to my TODO list :+1: 

If I remember correctly, there were some limits in game to not store more than 99 hours, I should remove them and then write code to show that third digit, I think it's possible yeah.
